/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"
#include "g_canvas.h"

static t_class *align_class;

typedef struct _align {
   t_object x_obj;
   t_canvas *x_canvas;
} t_align;

void align_xstep(t_align *x, t_floatarg f0){
  t_glist *glist = x->x_canvas;
  t_gobj*obj = NULL;

  int xmin = 0x7fffffff;

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      if(x1 < xmin) xmin = x1;
    }
  }

  int lastx = 0;
  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      if(lastx != 0)gobj_displace(obj, glist, lastx + f0 - x1, 0);
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      lastx = x2;
    }
  }
}

void align_left(t_align *x){
  t_glist*glist = x->x_canvas;
  t_gobj*obj = NULL;

  int xmin = 0x7fffffff;

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      if(x1 < xmin) xmin = x1;
    }
  }

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      gobj_displace(obj, glist, xmin - x1, 0);
    }
  }
}

void align_right(t_align *x){
  t_glist*glist = x->x_canvas;
  t_gobj*obj = NULL;

  int xmax = -0x7fffffff;

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      if(x2 > xmax) xmax = x2;
    }
  }

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      gobj_displace(obj, glist, xmax - x2, 0);
    }
  }
}

void align_center(t_align *x){
  t_glist*glist = x->x_canvas;
  t_gobj*obj = NULL;

  int xmax = -0x7fffffff;

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      if((x2 + x1)/2 > xmax) xmax = (x2 + x1) / 2;
    }
  }

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      gobj_displace(obj, glist, xmax - (x2 + x1)/2, 0);
    }
  }
}

void align_grid(t_align *x, t_floatarg f0){
  t_glist*glist = x->x_canvas;
  t_gobj*obj = NULL;

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      x1 = (x1%((int)f0) > f0/2)? f0 - x1%((int)f0) : -(x1%((int)f0));
      y1 = (y1%((int)f0) > f0/2)? f0 - y1%((int)f0) : -(y1%((int)f0));
      gobj_displace(obj, glist, x1, y1);
      }
  }
}

void align_ystep(t_align *x, t_floatarg f0){
  t_glist*glist = x->x_canvas;
  t_gobj*obj = NULL;

  int ymin = 0x7fffffff;

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      if(y1 < ymin) ymin = y1;
    }
  }

   int lasty = 0;
   for(obj=glist->gl_list; obj; obj=obj->g_next) {
      if(glist_isselected(glist, obj)) {
         int x1, y1, x2, y2;
         gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
         if(lasty != 0)gobj_displace(obj, glist, 0, lasty + f0 - y1);
         gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
         lasty = y2;
      }
   }
}

void align_top(t_align *x){
  t_glist*glist = x->x_canvas;
  t_gobj*obj = NULL;

  int ymin = 0x7fffffff;

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      if(y1 < ymin) ymin = y1;
    }
  }

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      gobj_displace(obj, glist, 0, ymin - y1);
    }
  }
}

void align_middle(t_align *x){
  t_glist*glist = x->x_canvas;
  t_gobj*obj = NULL;

  int ymax = -0x7fffffff;

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      if((y2 + y1)/2 > ymax) ymax = (y2 + y1) / 2;
    }
  }

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      gobj_displace(obj, glist, 0, ymax - (y2 + y1)/2);
    }
  }
}

void align_bottom(t_align *x){
  t_glist*glist = x->x_canvas;
  t_gobj*obj = NULL;

  int ymax = -0x7fffffff;

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      if(y2 > ymax) ymax = y2;
    }
  }

  for(obj=glist->gl_list; obj; obj=obj->g_next) {
    if(glist_isselected(glist, obj)) {
      int x1, y1, x2, y2;
      gobj_getrect(obj, glist, &x1, &y1, &x2, &y2);
      gobj_displace(obj, glist, 0, ymax - y2);
    }
  }
}

// Constructor of the class
void * align_new(void) {
   t_align *x = (t_align *) pd_new(align_class);
   t_glist *glist=(t_glist *)canvas_getcurrent();
   t_canvas *canvas=(t_canvas*)glist_getcanvas(glist);
   x->x_canvas = canvas;
   return (void *) x;
}

// Destroy the class
void align_destroy(t_align *x) {
//   post("You say good bye and I say hello");
   (void)x;
}

void align_setup(void) {
   align_class = class_new(gensym("align"),
      (t_newmethod) align_new, // Constructor
      (t_method) align_destroy, // Destructor
      sizeof (t_align),
      CLASS_DEFAULT,
      0);//Must always ends with a zero

   class_addmethod(align_class, (t_method) align_left, gensym("left"), 0);
   class_addmethod(align_class, (t_method) align_center, gensym("center"), 0);
   class_addmethod(align_class, (t_method) align_right, gensym("right"), 0);
   class_addmethod(align_class, (t_method) align_top, gensym("top"), 0);
   class_addmethod(align_class, (t_method) align_middle, gensym("middle"), 0);
   class_addmethod(align_class, (t_method) align_bottom, gensym("bottom"), 0);
	class_addmethod(align_class, (t_method) align_xstep, gensym("xstep"),A_DEFFLOAT,  0);
	class_addmethod(align_class, (t_method) align_ystep, gensym("ystep"),A_DEFFLOAT,  0);
	class_addmethod(align_class, (t_method) align_grid, gensym("grid"),A_DEFFLOAT,  0);
}

